version: "3.7"
services:
 backend:
  container_name: deployBackend
  
  restart: always
  build: 
   context: ./backend
   dockerfile: Dockerfile
  environment:
   PORT_BACKEND: 3000
   HOST_DB: database
   USER_DB: postgres
   PASSWORD_DB: 123456
   NAME_DB: ranking
   PORT_DB: 5432
  ports:
   - "3000:3000"
  links:
   - database
 frontend:
  container_name: deployFrontend
  restart: always
  build:
   context: ./frontend
   dockerfile: Dockerfile
  ports:
   - "5000:80"
  links:
   - backend
 database:
  container_name: deployDatabase
  restart: always
  build:
   context: ./database
   dockerfile: Dockerfile
  ports:
   - "5432:5432"
